# 공통 설정 파일
# 데이터, 피처, 전처리 등 모든 모델과 실험에서 공통으로 사용되는 설정

# 데이터 설정
data:
  file_path: "data/sourcedata/data.csv"
  encoding: "utf-8"
  na_values: ["", "nan", "NaN", "NULL", "null"]
  # 빠른 테스트를 위한 샘플링 설정
  sampling:
    enabled: false  # 샘플링 비활성화 (전체 데이터셋 사용)
    method: "id_based"  # ID 기반 샘플링
    sample_size: 10000  # 10,000명의 환자
    random_state: 42  # 재현성을 위한 시드

# 시계열 설정
time_series:
  id_column: "id"
  year_column: "yov"
  date_column: "dov"

# 피처 설정
features:
  # 타겟 컬럼 - suicide_a_next_year만 사용
  target_columns:
    - "suicide_a_next_year"
  
  # 타겟 변수명 정의 (하드코딩 제거를 위한 중앙화)
  target_variables:
    # 원본 타겟 변수명 (전처리 전)
    original_targets:
      # 연속형 점수
      score_targets:
        - "anxiety_score"
        - "depress_score" 
        - "sleep_score"
        - "comp"
      # 이진형 타겟
      binary_targets:
        - "suicide_t"
        - "suicide_a"
    
    # 다음 해 예측 타겟 (전처리 후)
    next_year_targets:
      # 연속형 점수
      score_targets:
        - "anxiety_score_next_year"
        - "depress_score_next_year" 
        - "sleep_score_next_year"
      # 이진형 타겟
      binary_targets:
        - "suicide_t_next_year"
        - "suicide_a_next_year"
  
  # 타겟 타입 정의 (자동 판단 대신 명시적 정의)
  target_types:
    # 회귀 타겟 (연속형 값 예측)
    regression_targets:
      - "anxiety_score_next_year"
      - "depress_score_next_year" 
      - "sleep_score_next_year"
    
    # 분류 타겟 (이진 분류)
    classification_targets:
      - "suicide_t_next_year"
      - "suicide_a_next_year"
  
  # 제외할 컬럼들
  exclude_columns:
    - "id"
    - "patient_id"
    - "visit_date"
    - "visit_year"
  
  # 범주형 변수 처리
  categorical_columns:
    - "gender"
    - "marital_status"
    - "education_level"
    - "income_level"
    - "residence_type"
    - "insurance_type"
    - "primary_diagnosis"
    - "comorbidity"
    - "medication_type"
    - "treatment_type"
    - "follow_up_status"
  
  # 선택된 피처 목록 - 원본 데이터 기준으로 수정
  selected_features: [
    # 기본 인구학적 정보 (원본 데이터에 존재)
    "age", "sex",
    
    # 정신 건강 점수 (원본 데이터에 존재)
    "anxiety_score", "depress_score", "sleep_score", "comp",
    
    # 자살 관련 변수 (원본 데이터에 존재)
    # "suicide_t", "suicide_a",  # 제외
    
    # 정신과 분류 (원본 데이터에 존재)
    "psychia_cate",
    
    # 시간 기반 피처 (피처 엔지니어링으로 생성)
    "month", "day_of_week", "day_of_year",
    
    # 과거 이력 피처 (피처 엔지니어링으로 생성) - 2년, 3년 윈도우
    "anxiety_score_rolling_mean_2y", "anxiety_score_rolling_std_2y", "anxiety_score_yoy_change",
    "depress_score_rolling_mean_2y", "depress_score_rolling_std_2y", "depress_score_yoy_change",
    "sleep_score_rolling_mean_2y", "sleep_score_rolling_std_2y", "sleep_score_yoy_change",
    
    # 3년 윈도우 피처 (피처 엔지니어링으로 생성)
    "anxiety_score_rolling_mean_3y", "anxiety_score_rolling_std_3y",
    "depress_score_rolling_mean_3y", "depress_score_rolling_std_3y",
    "sleep_score_rolling_mean_3y", "sleep_score_rolling_std_3y",
    
    # comp 관련 피처 (피처 엔지니어링으로 생성)
    "comp_rolling_mean_2y", "comp_rolling_std_2y", "comp_yoy_change",
    "comp_rolling_mean_3y", "comp_rolling_std_3y",
    
    # 지연 피처 (피처 엔지니어링으로 생성)
    "anxiety_score_lag_1", "anxiety_score_lag_2",
    "depress_score_lag_1", "depress_score_lag_2",
    "sleep_score_lag_1", "sleep_score_lag_2",
    "comp_lag_1", "comp_lag_2",
    
    # 결측치 플래그 (전처리에서 생성)
    "anxiety_score_missing", "depress_score_missing", "sleep_score_missing",
    
    # next_year 타겟 변수들은 제외 (데이터 누수 방지)
    # "anxiety_score_next_year", "depress_score_next_year", "sleep_score_next_year", "comp_next_year",
    # "suicide_t_next_year", "suicide_a_next_year"
  ]
  
  # 기존 피처 검증 설정
  validation:
    scope: "sample"  # "sample", "full", "none"
    sample_size: 100  # scope가 "sample"일 때 검증할 ID 수
  
  # Feature Engineering 제어 - 통합 후 활성화
  enable_feature_engineering: true  # true: 활성화, false: 비활성화
  
  # 지연 피처 설정 - 활성화
  enable_lagged_features: true
  lag_periods: [1, 2]
  lagged_features:
    columns: ["anxiety_score", "depress_score", "sleep_score", "comp"]
  
  # 이동 통계 피처 설정 - 활성화
  enable_rolling_stats: true
  rolling_stats:
    window_sizes: [2, 3]
    columns: ["anxiety_score", "depress_score", "sleep_score", "comp"]

# 전처리 설정
preprocessing:
  # 시계열 보간 설정
  time_series_imputation:
    columns: ["anxiety_score", "depress_score", "sleep_score", "comp"]
    fallback_strategy: "mean"
  
  # 결측치 플래그 설정
  missing_flags:
    enabled: true  # 결측치 플래그 생성 활성화
    columns: ["sleep_score", "depress_score", "anxiety_score"]  # 플래그 생성 대상 컬럼
  
  # 수치형 결측치 처리
  numerical_imputation:
    strategy: "median"  # "mean", "median", "constant"
    columns: ["anxiety_score", "depress_score", "sleep_score", "comp", "age"]
  
  # 범주형 결측치 처리
  categorical_imputation:
    strategy: "most_frequent"  # "most_frequent", "constant"
    columns: ["sex"]
  
  # 범주형 인코딩 설정
  categorical_encoding:
    method: "ordinal"  # "onehot", "ordinal", "none"
  
  # 결측치 처리
  missing_value_strategy: "median"
  
  # 이상치 처리
  outlier_detection:
    method: "iqr"
    threshold: 1.5
  
  # 스케일링
  scaling:
    method: "none"  # 트리 기반 모델을 위해 스케일링 비활성화
    with_mean: false
    with_std: false
  
  # 피처 선택
  feature_selection:
    method: "variance_threshold"
    threshold: 0.01 

# 모델 설정
model:
  # scale_pos_weight 자동 계산 제어
  auto_scale_pos_weight: false  # false: 튜닝된 값 사용, true: 자동 계산 사용 