# 검증 설정 파일
# 데이터 분할, 교차 검증, 시계열 처리 등 검증 관련 설정

# 데이터 분할 설정
data_split:
  test_ids_ratio: 0.15  # 최종 테스트 세트에 사용할 ID 비율
  random_state: 42      # 재현성을 위한 시드
  method: "stratified_kfold"
  n_splits: 5
  test_size: 0.2
  val_size: 0.2

# 검증 전략 설정
validation:
  strategy: "group_kfold"  # "time_series_walk_forward", "time_series_group_kfold", "group_kfold"
  num_cv_folds: 3  # 디버깅용으로 3폴드로 변경
  test_size: 0.15  # 테스트 세트 비율
  random_state: 42
  
  # 모든 전략에 공통 적용될 수 있는 파라미터
  val_ids_ratio: 0.15  # 각 폴드 내에서 검증에 사용할 ID 비율

  # "time_series_walk_forward" 전략 전용 파라미터
  validation_start_year: 2021  # Walk-Forward 검증 시작 연도
  min_train_years: 3           # 최소 훈련 연도 수 (Walk-Forward 시)
  max_train_years: 8           # 최대 훈련 연도 수 (Walk-Forward 시)

# 시계열 설정
time_series:
  date_column: "dov"  # 날짜 컬럼명
  year_column: "yov"  # 연도 컬럼명
  id_column: "id"     # 개인 ID 컬럼명 