# 하이퍼파라미터 튜닝 실험 템플릿
# 새로운 튜닝 실험을 시작할 때 참고할 템플릿

# 실험 설정
experiment:
  name: "tuning_experiment"
  description: "하이퍼파라미터 튜닝 실험"
  tags:
    - "tuning"
    - "optimization"

# 튜닝 설정
tuning:
  direction: "maximize"  # "maximize" 또는 "minimize"
  n_trials: 50  # 튜닝 횟수
  n_jobs: 1  # 병렬 처리 설정
  
  # 조기 종료 설정
  early_stopping:
    enabled: true
    patience: 20
    min_trials: 30

# Optuna Sampler 설정
sampler:
  type: "tpe"  # "tpe", "random", "cmaes", "nsgaii", "qmc"
  
  # TPE 설정
  tpe:
    n_startup_trials: 10
    n_ei_candidates: 24
    multivariate: true
    group: false

# 하이퍼파라미터 검색 범위 (모델별로 설정)
# xgboost_params:
#   n_estimators:
#     type: "int"
#     low: 50
#     high: 1000
#     log: false
#   
#   max_depth:
#     type: "int"
#     low: 3
#     high: 12
#     log: false
#   
#   learning_rate:
#     type: "float"
#     low: 0.01
#     high: 0.3
#     log: true

# 평가 지표 설정
evaluation:
  primary_metric: "f1_score"
  secondary_metrics: ["recall", "precision", "balanced_accuracy", "roc_auc"]
  
  # 교차 검증 설정
  cv:
    strategy: "group_kfold"
    n_folds: 5
    shuffle: false

# 결과 저장 설정
results:
  save_best_model: true
  model_save_path: "models/best_tuned_model.joblib"
  save_study: true
  study_save_path: "models/optuna_study.pkl"
  create_plots: true
  plots_save_path: "data/tuning_results/"

# MLflow 연동 설정
mlflow:
  experiment_name: "hyperparameter_tuning"
  nested_runs: true
  log_optimization: true 