# CatBoost 모델 설정 파일
# CatBoost 모델 전용 설정

# 모델 설정
model:
  model_type: "catboost"
  
  # CatBoost 모델 파라미터 (자살 예측 최적화)
  catboost:
    # 기본 파라미터 (참고 repository 기반)
    iterations: 300  # 100 -> 300으로 증가
    depth: 8         # 6 -> 8로 증가
    learning_rate: 0.1
    l2_leaf_reg: 3
    
    # 분류를 위한 loss function과 eval_metric 설정
    loss_function: "Logloss"  # 분류용 loss function
    eval_metric: "Logloss"    # 분류용 평가 지표
    
    # 범주형 변수 처리
    cat_features: []  # 자동 감지
    cat_l2: 10.0
    cat_smooth: 10.0
    max_cat_threshold: 32
    one_hot_max_size: 10
    
    # 과적합 방지
    random_strength: 1
    bagging_temperature: 1
    border_count: 254
    feature_border_type: "GreedyLogSum"
    
    # Early Stopping
    early_stopping_rounds: 10
    
    # 성능 최적화
    verbose: false
    
    # 불균형 데이터 처리 (강화)
    # class_weights: [1, 1]  # (사용하지 않음)
    auto_class_weights: "Balanced"
    scale_pos_weight: 1.0  # 자동 계산됨 (코드에서 _calculate_scale_pos_weight 사용)
    
    # Focal Loss 설정 (CatBoost는 직접 지원하지 않지만 설정을 인식)
    use_focal_loss: false  # Focal Loss 사용 여부 (true/false)
    focal_loss:
      alpha: 0.25  # 클래스 가중치 (0 < alpha < 1). 소수 클래스에 더 큰 가중치
      gamma: 2.0   # 포커싱 파라미터 (gamma >= 0). 쉬운 샘플의 기여도를 낮춤
    
    # 부스팅 파라미터
    boosting_type: "Plain"
    bootstrap_type: "Bernoulli"
    subsample: 0.8
    
    # 정규화
    rsm: 0.8  # feature_fraction과 동일
    leaf_estimation_method: "Newton"
    
    # 랜덤성
    random_seed: 42
    bootstrap_seed: 42
    
    # 고급 파라미터
    min_data_in_leaf: 1
    max_leaves: 31
    grow_policy: "SymmetricTree"
    min_fold_size: 1
    leaf_estimation_iterations: 1
    fold_permutation_block: 1
    leaf_estimation_backtracking: "AnyImprovement"
    best_model_min_trees: 1
    model_shrink_rate: 0
    model_shrink_mode: "Constant"
    langevin: false
    diffusion_temperature: 10000
    posterior_sampling: false
    boost_from_average: true
    allow_const_label: false
    score_function: "Cosine"
    monotone_constraints: ""
    penalties_coefficient: 1
    first_feature_use_penalties: 0
    model_size_reg: 0.5
    per_float_feature_quantization: ""
    eval_fraction: 0
    fixed_binary_splits: null
    ignored_features: null
    train_dir: null
    name: "experiment"
    prediction_type: "Probability"
    fold_len_multiplier: 2
    has_time: false
    allow_writing_files: false
    save_snapshot: false
    snapshot_file: null
    snapshot_interval: 600
    gradient_iterations: 1
    sampling_unit: "Object"
    mvs_reg: 0.1
    thread_count: 28   # 병렬처리 코어 수

# 불균형 데이터 처리 설정
imbalanced_data:
  resampling:
    enabled: false  # 기본값, 실험에서 활성화
    method: "smote"  # "smote", "borderline_smote", "adasyn", "under_sampling"
    
    # SMOTE 설정
    smote:
      k_neighbors: 5
      sampling_strategy: "auto"
      
    # Borderline SMOTE 설정
    borderline_smote:
      k_neighbors: 5
      sampling_strategy: "auto"
      m_neighbors: 10
      
    # ADASYN 설정
    adasyn:
      k_neighbors: 5
      sampling_strategy: "auto"
      n_neighbors: 5
      
    # 언더샘플링 설정
    under_sampling:
      strategy: "random"
      sampling_strategy: "auto"
  
  # CatBoost 내장 불균형 처리
  class_weights: "Balanced"  # "Balanced", "SqrtBalanced", "None"
  auto_class_weights: "Balanced"
  scale_pos_weight: 1.0  # 자동 계산됨 