# LightGBM 모델 설정 파일
# LightGBM 모델 전용 설정

# 모델 설정
model:
  model_type: "lightgbm"
  
  # LightGBM 모델 파라미터 (자살 예측 최적화)
  lightgbm:
    n_estimators: 300  # 100 -> 300으로 증가
    max_depth: 15      # 6 -> 15로 증가
    learning_rate: 0.1
    subsample: 0.9     # 0.8 -> 0.9로 증가
    colsample_bytree: 0.9  # 0.8 -> 0.9로 증가
    min_child_samples: 20
    min_child_weight: 1e-3
    subsample_freq: 1
    reg_alpha: 0.1
    reg_lambda: 0.1
    scale_pos_weight: 1.0  # 자동 계산됨 (코드에서 _calculate_scale_pos_weight 사용)
    is_unbalance: false  # scale_pos_weight와 충돌 방지
    class_weight: "balanced"
    early_stopping_rounds: 10
    verbose: -1
    n_jobs: 4   # 병렬처리 코어 수 (안전한 기본값으로 조정)

    # Focal Loss 설정
    use_focal_loss: false  # Focal Loss 사용 여부 (true/false)
    focal_loss:
      alpha: 0.25  # 클래스 가중치 (0 < alpha < 1). 소수 클래스에 더 큰 가중치
      gamma: 2.0   # 포커싱 파라미터 (gamma >= 0). 쉬운 샘플의 기여도를 낮춤

# 불균형 데이터 처리 설정
imbalanced_data:
  resampling:
    enabled: false  # 기본값, 실험에서 활성화
    method: "smote"  # "smote", "borderline_smote", "adasyn", "under_sampling"
    
    # SMOTE 설정
    smote:
      k_neighbors: 5
      sampling_strategy: "auto"
      
    # Borderline SMOTE 설정
    borderline_smote:
      k_neighbors: 5
      sampling_strategy: "auto"
      m_neighbors: 10
      
    # ADASYN 설정
    adasyn:
      k_neighbors: 5
      sampling_strategy: "auto"
      n_neighbors: 5
      
    # 언더샘플링 설정
    under_sampling:
      strategy: "random"
      sampling_strategy: "auto"
  
  # LightGBM 내장 불균형 처리
  class_weight: "balanced"
  scale_pos_weight: 1.0  # 자동 계산됨
  is_unbalance: true 