# Focal Loss 실험 설정 파일
# 기본 설정을 복사하고 Focal Loss를 활성화한 버전

# 데이터 분할 설정
data_split:
  test_ids_ratio: 0.15
  random_state: 42

# 검증 전략 설정
validation:
  strategy: "group_kfold"
  num_cv_folds: 3
  test_size: 0.15
  random_state: 42
  val_ids_ratio: 0.15

# 시계열 설정
time_series:
  date_column: "dov"
  year_column: "yov"
  id_column: "id"

# 전처리 설정
preprocessing:
  time_series_imputation:
    columns: ["anxiety_score", "depress_score", "sleep_score", "comp", "suicide_t", "suicide_a"]
    fallback_strategy: "mean"
  
  numerical_imputation:
    strategy: "mean"
    columns: ["anxiety_score", "depress_score", "sleep_score", "comp", "age"]
  
  categorical_imputation:
    strategy: "most_frequent"
    columns: ["sex", "psychia_cate"]
  
  categorical_encoding:
    method: "ordinal"

# 피처 엔지니어링 설정
features:
  target_columns: ["suicide_a_next_year"]
  
  selected_features: [
    "age", "sex",
    "comp", "anxiety_score", "depress_score", "sleep_score",
    "suicide_t", "suicide_a",
    "psychia_cate",
    "month", "day_of_week", "day_of_year",
    "anxiety_score_rolling_mean_2y", "anxiety_score_rolling_std_2y", "anxiety_score_yoy_change",
    "depress_score_rolling_mean_2y", "depress_score_rolling_std_2y", "depress_score_yoy_change",
    "sleep_score_rolling_mean_2y", "sleep_score_rolling_std_2y", "sleep_score_yoy_change",
    "comp_rolling_mean_2y", "comp_rolling_std_2y", "comp_yoy_change"
  ]
  
  validation:
    scope: "sample"
    sample_size: 10
  
  enable_lagged_features: false
  lag_periods: [1, 2, 3]
  lagged_features:
    columns: ["anxiety_score", "depress_score", "sleep_score", "comp"]
  
  enable_rolling_stats: false
  rolling_stats:
    window_sizes: [2, 3]
    columns: ["anxiety_score", "depress_score", "sleep_score", "comp"]

# 모델 설정 - Focal Loss 활성화
model:
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    min_child_weight: 1
    scale_pos_weight: 1.0
    early_stopping_rounds: 10
    verbose: 0
    
    # Focal Loss 활성화
    use_focal_loss: true  # Focal Loss 사용
    focal_loss:
      alpha: 0.25  # 소수 클래스 가중치 (0.25 = 소수 클래스에 3배 가중치)
      gamma: 2.0   # 포커싱 파라미터 (쉬운 샘플의 기여도를 낮춤)

# 학습 설정
training:
  early_stopping: true
  patience: 10
  handle_imbalance: true
  save_best_model: true
  model_save_path: "models/"

# 평가 설정
evaluation:
  regression_metrics: ["mae", "rmse", "r2"]
  classification_metrics: ["precision", "recall", "f1", "roc_auc"]
  save_predictions: true
  save_feature_importance: true

# 로깅 설정
logging:
  log_splits_info: true
  log_fold_details: true 