# LightGBM 모델 설정 파일
# 빠른 학습 속도와 높은 성능을 위한 최적화된 파라미터

# 데이터 설정
data:
  file_path: "data/processed_data.csv"
  encoding: "utf-8"
  na_values: ["", "nan", "NaN", "NULL", "null"]

# 피처 설정
features:
  target_columns:
    - "anxiety_score_next_year"
    - "depress_score_next_year"
    - "sleep_score_next_year"
    - "suicide_t_next_year"
    - "suicide_a_next_year"
  
  # 제외할 컬럼들
  exclude_columns:
    - "id"
    - "patient_id"
    - "visit_date"
    - "visit_year"
  
  # 범주형 변수 처리
  categorical_columns:
    - "gender"
    - "marital_status"
    - "education_level"
    - "income_level"
    - "residence_type"
    - "insurance_type"
    - "primary_diagnosis"
    - "comorbidity"
    - "medication_type"
    - "treatment_type"
    - "follow_up_status"

# 데이터 분할 설정
data_split:
  method: "stratified_kfold"
  n_splits: 5
  random_state: 42
  test_size: 0.2
  val_size: 0.2

# 모델 설정
model:
  model_type: "lightgbm"
  
  # LightGBM 특화 파라미터
  lightgbm:
    # 기본 파라미터
    num_leaves: 31
    learning_rate: 0.1
    feature_fraction: 0.9
    bagging_fraction: 0.8
    bagging_freq: 5
    min_data_in_leaf: 20
    min_sum_hessian_in_leaf: 1e-3
    
    # 정규화 파라미터
    lambda_l1: 0.1
    lambda_l2: 0.1
    
    # 성능 최적화
    num_threads: -1  # 모든 CPU 코어 사용
    verbose: -1      # 로그 출력 최소화
    
    # Early Stopping
    early_stopping_rounds: 10
    
    # 범주형 변수 처리
    max_cat_threshold: 32
    cat_smooth: 10.0
    cat_l2: 10.0
    
    # 불균형 데이터 처리
    is_unbalance: true
    scale_pos_weight: 1.0
    
    # 부스팅 파라미터
    boosting_type: "gbdt"
    objective: "binary"  # 분류의 경우, 회귀는 자동 설정
    metric: "binary_logloss"  # 분류의 경우, 회귀는 자동 설정
    
    # 과적합 방지
    max_depth: 6
    min_gain_to_split: 0.0
    min_child_samples: 20
    
    # 랜덤성
    bagging_seed: 42
    feature_fraction_seed: 42
    drop_seed: 42
    data_random_seed: 42

    # Focal Loss 설정
    use_focal_loss: false  # Focal Loss 사용 여부 (true/false)
    focal_loss:
      alpha: 0.25  # 클래스 가중치 (0 < alpha < 1). 소수 클래스에 더 큰 가중치
      gamma: 2.0   # 포커싱 파라미터 (gamma >= 0). 쉬운 샘플의 기여도를 낮춤

# 전처리 설정
preprocessing:
  # 결측치 처리
  missing_value_strategy: "median"
  
  # 이상치 처리
  outlier_detection:
    method: "iqr"
    threshold: 1.5
  
  # 스케일링
  scaling:
    method: "robust"  # RobustScaler 사용
    with_mean: true
    with_std: true
  
  # 피처 선택
  feature_selection:
    method: "variance_threshold"
    threshold: 0.01

# 평가 설정
evaluation:
  # 분류 메트릭
  classification_metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "auc"
    - "roc_auc"
    - "average_precision"
  
  # 회귀 메트릭
  regression_metrics:
    - "mse"
    - "rmse"
    - "mae"
    - "r2"
    - "explained_variance"
  
  # 교차 검증
  cv_metrics:
    - "accuracy"
    - "f1"
    - "auc"
    - "rmse"
    - "r2"

# 출력 설정
output:
  directory: "results/lightgbm"
  save_model: true
  save_predictions: true
  save_feature_importance: true
  save_confusion_matrix: true
  save_roc_curve: true
  save_precision_recall_curve: true

# 로깅 설정
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/lightgbm_experiment.log"

# 실험 설정
experiment:
  name: "lightgbm_suicide_prediction"
  description: "LightGBM을 사용한 자살 위험 예측 모델"
  tags:
    - "lightgbm"
    - "suicide_prediction"
    - "healthcare"
    - "classification"
    - "regression"
  
  # 하이퍼파라미터 튜닝
  hyperparameter_tuning:
    enabled: false
    method: "optuna"
    n_trials: 100
    timeout: 3600  # 1시간
    
    # 튜닝할 파라미터
    parameters:
      num_leaves:
        type: "int"
        low: 10
        high: 100
      learning_rate:
        type: "float"
        low: 0.01
        high: 0.3
      feature_fraction:
        type: "float"
        low: 0.5
        high: 1.0
      bagging_fraction:
        type: "float"
        low: 0.5
        high: 1.0
      lambda_l1:
        type: "float"
        low: 0.0
        high: 1.0
      lambda_l2:
        type: "float"
        low: 0.0
        high: 1.0 