# Random Forest 모델 설정 파일
# 해석 가능성과 안정성을 위한 최적화된 파라미터

# 데이터 설정
data:
  file_path: "data/processed_data.csv"
  encoding: "utf-8"
  na_values: ["", "nan", "NaN", "NULL", "null"]

# 피처 설정
features:
  target_columns:
    - "anxiety_score_next_year"
    - "depress_score_next_year"
    - "sleep_score_next_year"
    - "suicide_t_next_year"
    - "suicide_a_next_year"
  
  # 제외할 컬럼들
  exclude_columns:
    - "id"
    - "patient_id"
    - "visit_date"
    - "visit_year"
  
  # 범주형 변수 처리
  categorical_columns:
    - "gender"
    - "marital_status"
    - "education_level"
    - "income_level"
    - "residence_type"
    - "insurance_type"
    - "primary_diagnosis"
    - "comorbidity"
    - "medication_type"
    - "treatment_type"
    - "follow_up_status"

# 데이터 분할 설정
data_split:
  method: "stratified_kfold"
  n_splits: 5
  random_state: 42
  test_size: 0.2
  val_size: 0.2

# 모델 설정
model:
  model_type: "random_forest"
  
  # Random Forest 특화 파라미터
  random_forest:
    # 기본 파라미터
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: "sqrt"
    
    # 부트스트랩 설정
    bootstrap: true
    oob_score: true
    max_samples: 0.8
    
    # 불균형 데이터 처리
    class_weight: "balanced"
    
    # 성능 최적화
    n_jobs: -1  # 모든 CPU 코어 사용
    random_state: 42
    
    # 과적합 방지
    min_impurity_decrease: 0.0
    min_weight_fraction_leaf: 0.0
    max_leaf_nodes: null
    
    # 랜덤성
    ccp_alpha: 0.0
    
    # 분류 특화 파라미터
    criterion: "gini"  # 분류의 경우
    # criterion: "squared_error"  # 회귀의 경우
    
    # 회귀 특화 파라미터
    max_features_regression: "sqrt"
    min_impurity_decrease_regression: 0.0
    
    # Focal Loss 설정 (Random Forest는 직접 지원하지 않지만 설정을 인식)
    use_focal_loss: false  # Focal Loss 사용 여부 (true/false)
    focal_loss:
      alpha: 0.25  # 클래스 가중치 (0 < alpha < 1). 소수 클래스에 더 큰 가중치
      gamma: 2.0   # 포커싱 파라미터 (gamma >= 0). 쉬운 샘플의 기여도를 낮춤

# 전처리 설정
preprocessing:
  # 결측치 처리
  missing_value_strategy: "median"
  
  # 이상치 처리
  outlier_detection:
    method: "iqr"
    threshold: 1.5
  
  # 스케일링 (Random Forest는 스케일링이 필요 없지만, 일관성을 위해 포함)
  scaling:
    method: "none"  # Random Forest는 스케일링 불필요
    with_mean: false
    with_std: false
  
  # 피처 선택
  feature_selection:
    method: "variance_threshold"
    threshold: 0.01
  
  # 범주형 변수 인코딩
  categorical_encoding:
    method: "onehot"  # One-Hot Encoding 사용
    drop_first: true
    sparse: false

# 평가 설정
evaluation:
  # 분류 메트릭
  classification_metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "auc"
    - "roc_auc"
    - "average_precision"
    - "balanced_accuracy"
  
  # 회귀 메트릭
  regression_metrics:
    - "mse"
    - "rmse"
    - "mae"
    - "r2"
    - "explained_variance"
    - "mean_absolute_percentage_error"
  
  # 교차 검증
  cv_metrics:
    - "accuracy"
    - "f1"
    - "auc"
    - "rmse"
    - "r2"
    - "balanced_accuracy"
  
  # 모델 해석 메트릭
  interpretability_metrics:
    - "feature_importance"
    - "permutation_importance"
    - "partial_dependence"
    - "shap_values"

# 출력 설정
output:
  directory: "results/random_forest"
  save_model: true
  save_predictions: true
  save_feature_importance: true
  save_confusion_matrix: true
  save_roc_curve: true
  save_precision_recall_curve: true
  save_partial_dependence: true
  save_shap_values: true

# 로깅 설정
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/random_forest_experiment.log"

# 실험 설정
experiment:
  name: "random_forest_suicide_prediction"
  description: "Random Forest를 사용한 자살 위험 예측 모델 - 해석 가능성과 안정성 중점"
  tags:
    - "random_forest"
    - "suicide_prediction"
    - "healthcare"
    - "classification"
    - "regression"
    - "interpretability"
  
  # 하이퍼파라미터 튜닝
  hyperparameter_tuning:
    enabled: false
    method: "optuna"
    n_trials: 100
    timeout: 3600  # 1시간
    
    # 튜닝할 파라미터
    parameters:
      n_estimators:
        type: "int"
        low: 50
        high: 300
      max_depth:
        type: "int"
        low: 5
        high: 20
      min_samples_split:
        type: "int"
        low: 2
        high: 10
      min_samples_leaf:
        type: "int"
        low: 1
        high: 5
      max_features:
        type: "categorical"
        choices: ["sqrt", "log2", "auto"]
  
  # 모델 해석 설정
  interpretability:
    # SHAP 값 계산
    calculate_shap: true
    shap_background_samples: 100
    
    # 부분 의존성 플롯
    partial_dependence: true
    pd_features: ["age", "anxiety_score", "depress_score", "sleep_score"]
    
    # 순열 중요도
    permutation_importance: true
    n_repeats: 5
    
    # 피처 중요도 시각화
    feature_importance_plot: true
    top_n_features: 20

# 모델 앙상블 설정 (선택사항)
ensemble:
  enabled: false
  method: "voting"
  estimators:
    - name: "rf1"
      params:
        n_estimators: 100
        max_depth: 10
    - name: "rf2"
      params:
        n_estimators: 200
        max_depth: 15
    - name: "rf3"
      params:
        n_estimators: 150
        max_depth: 12
  
  voting_method: "soft"  # 분류의 경우
  # voting_method: "average"  # 회귀의 경우 